// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  eventType: __t.string().name("event_type"),
  robotId: __t.u32().name("robot_id"),
  payload: __t.string(),
  hash: __t.string(),
  prevHash: __t.string().name("prev_hash"),
  operatorId: __t.string().name("operator_id"),
  timestamp: __t.timestamp(),
});
