// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  robotId: __t.u32().name("robot_id"),
  action: __t.string(),
  manualReference: __t.string().name("manual_reference"),
  torqueSpec: __t.string().name("torque_spec"),
  estimatedMinutes: __t.u32().name("estimated_minutes"),
  status: __t.string(),
  assignedTo: __t.string().name("assigned_to"),
});
