// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  materialName: __t.string().name("material_name"),
  quantityKg: __t.f32().name("quantity_kg"),
  supplierCode: __t.string().name("supplier_code"),
  status: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
  hash: __t.string(),
});
