// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  parameter: __t.string(),
  deltaPercent: __t.f32().name("delta_percent"),
  projectedOutput: __t.f32().name("projected_output"),
  riskScore: __t.f32().name("risk_score"),
  faultProbability: __t.f32().name("fault_probability"),
  ranBy: __t.string().name("ran_by"),
  ranAt: __t.timestamp().name("ran_at"),
});
