// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AuditLog = __t.object("AuditLog", {
  id: __t.u64(),
  eventType: __t.string(),
  robotId: __t.u32(),
  payload: __t.string(),
  hash: __t.string(),
  prevHash: __t.string(),
  operatorId: __t.string(),
  timestamp: __t.timestamp(),
});
export type AuditLog = __Infer<typeof AuditLog>;

export const EnergyLog = __t.object("EnergyLog", {
  id: __t.u64(),
  robotId: __t.u32(),
  zone: __t.string(),
  consumptionKw: __t.f32(),
  shift: __t.string(),
  timestamp: __t.timestamp(),
});
export type EnergyLog = __Infer<typeof EnergyLog>;

export const MaintenanceAction = __t.object("MaintenanceAction", {
  id: __t.u64(),
  robotId: __t.u32(),
  action: __t.string(),
  manualReference: __t.string(),
  torqueSpec: __t.string(),
  estimatedMinutes: __t.u32(),
  status: __t.string(),
  assignedTo: __t.string(),
});
export type MaintenanceAction = __Infer<typeof MaintenanceAction>;

export const Material = __t.object("Material", {
  id: __t.u32(),
  name: __t.string(),
  quantityPercent: __t.f32(),
  consumptionRatePerHour: __t.f32(),
  lastUpdated: __t.timestamp(),
});
export type Material = __Infer<typeof Material>;

export const Operator = __t.object("Operator", {
  identity: __t.identity(),
  name: __t.string(),
  role: __t.string(),
  zoneAccess: __t.string(),
  lastActive: __t.timestamp(),
});
export type Operator = __Infer<typeof Operator>;

export const PurchaseOrder = __t.object("PurchaseOrder", {
  id: __t.u64(),
  materialName: __t.string(),
  quantityKg: __t.f32(),
  supplierCode: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
  hash: __t.string(),
});
export type PurchaseOrder = __Infer<typeof PurchaseOrder>;

export const Robot = __t.object("Robot", {
  id: __t.u32(),
  name: __t.string(),
  zone: __t.string(),
  status: __t.string(),
  temperature: __t.f32(),
  vibration: __t.f32(),
  energyKw: __t.f32(),
  lastUpdated: __t.timestamp(),
});
export type Robot = __Infer<typeof Robot>;

export const SensorReading = __t.object("SensorReading", {
  id: __t.u64(),
  robotId: __t.u32(),
  readingType: __t.string(),
  value: __t.f32(),
  timestamp: __t.timestamp(),
});
export type SensorReading = __Infer<typeof SensorReading>;

export const Simulation = __t.object("Simulation", {
  id: __t.u64(),
  parameter: __t.string(),
  deltaPercent: __t.f32(),
  projectedOutput: __t.f32(),
  riskScore: __t.f32(),
  faultProbability: __t.f32(),
  ranBy: __t.string(),
  ranAt: __t.timestamp(),
});
export type Simulation = __Infer<typeof Simulation>;

