// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ConsumeMaterialReducer from "../consume_material_reducer";
import EmergencyStopReducer from "../emergency_stop_reducer";
import InjectAnomalyReducer from "../inject_anomaly_reducer";
import LogEnergyReducer from "../log_energy_reducer";
import ResolveAnomalyReducer from "../resolve_anomaly_reducer";
import RunSimulationReducer from "../run_simulation_reducer";
import SimulateSensorDriftReducer from "../simulate_sensor_drift_reducer";
import UpdateRobotSensorReducer from "../update_robot_sensor_reducer";

export type ConsumeMaterialParams = __Infer<typeof ConsumeMaterialReducer>;
export type EmergencyStopParams = __Infer<typeof EmergencyStopReducer>;
export type InjectAnomalyParams = __Infer<typeof InjectAnomalyReducer>;
export type LogEnergyParams = __Infer<typeof LogEnergyReducer>;
export type ResolveAnomalyParams = __Infer<typeof ResolveAnomalyReducer>;
export type RunSimulationParams = __Infer<typeof RunSimulationReducer>;
export type SimulateSensorDriftParams = __Infer<typeof SimulateSensorDriftReducer>;
export type UpdateRobotSensorParams = __Infer<typeof UpdateRobotSensorReducer>;

